steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/halogen-episode-455311-t4/ai-game-app/app:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/halogen-episode-455311-t4/ai-game-app/app:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/halogen-episode-455311-t4/ai-game-app/app'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'game-ai-website'
      - '--image=us-central1-docker.pkg.dev/halogen-episode-455311-t4/ai-game-app/app:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=halogen-episode-455311-t4:us-central1:game-database'
      - '--set-env-vars=ENVIRONMENT=production'
      - >-
        --set-secrets=DB_SOCKET_PATH=DB_HOST:latest,DB_NAME=DB_NAME:latest,DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest

images:
  - 'us-central1-docker.pkg.dev/halogen-episode-455311-t4/ai-game-app/app:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/halogen-episode-455311-t4/ai-game-app/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
