name: Dependency Submission

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  submit-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: pip install pip-tools

      - uses: actions/component-detection-dependency-submission-action@v0
        with:
          detectors: PipReport
        continue-on-error: true
